sudo: required
services:
  - docker

before_install: 
  - docker build -t aseadadocker/docker-react-rev -f Dockerfile.dev .

script: 
  - docker run aseadadocker/docker-react-rev npm test -- --coverage --watchAll=false